### ISSUE TITLE
Can you make a Cookie Extension?

### ISSUE THREAD

**Issue by Quartonos** [SharkPool-SP/SharkPools-Extensions#100]
A Cookie i mean the save files in websites

**Comment by SharkPool-SP** [comment]
Cookies suck and can only store very little bits of info.

Use local storage or indexDB

**Comment by Quartonos** [comment]
where i found indexDB?

**Comment by SharkPool-SP** [comment]
> where i found indexDB?

Misty's gallery, should show on Google
