### ISSUE TITLE
Sprite Effects: "Color-Interpolation sRBG" Not Working When Packaged

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#101]
I notice that the "color-interpolation-filters="sRGB" is not working when packaged on electron windows.
I believe that the electron chrome are not compatible, but who knows.

On Turbowarp:
![image](https://github.com/user-attachments/assets/bb5643ca-8c38-4444-9596-1c6f2185d547)

Electron Packaged:
![image](https://github.com/user-attachments/assets/49064c0c-7f8a-44a7-b677-134d36987644)

Also reported this on Turbowarp Packager Issues, Maybe you could fix it?

**Comment by SharkPool-SP** [comment]
Make an issue here:

https://github.com/electron/electron

This isn't something I can fix
