### ISSUE TITLE
Extra Control: Frame rate drop while using Call()

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#103]
There is a massive framedrop when you use call() block many times on other sprites, I'm suggesting a optimization for this block since I use this block a lot.

**Comment by SharkPool-SP** [comment]
Seems fine to me? Theres nothing to optimize, theres a good chance that its an issue with your code, like the name youre inputting for the branch

**Comment by YogaindoCR** [comment]
> Seems fine to me? Theres nothing to optimize, theres a good chance that its an issue with your code, like the name youre inputting for the branch

Well...  I use it like a 100 of them, some of them are on a busy sprites (Sprite with many Clones) and probably that's why it froze for like a 80ms everytime a call() block run. The problem is, I needed to use this block for certain condition. Cuz the normal broadcast one are always resseted everytime a new call run.

Also for the name, did using a simple like from "Y Smoothing" to "Ysm" can improve the speed?

**Comment by SharkPool-SP** [comment]
No, the naming won't change anything. I suggest you go back to using messages.

Messages+ has an option to make a broadcast not restart on a new call. Rather, it waits for it to finish

**Comment by YogaindoCR** [comment]
> No, the naming won't change anything. I suggest you go back to using messages.
> 
> Messages+ has an option to make a broadcast not restart on a new call. Rather, it waits for it to finish

Wait really? Can I know what the it is?

**Comment by SharkPool-SP** [comment]
> > No, the naming won't change anything. I suggest you go back to using messages.
> 
> > 
> 
> > Messages+ has an option to make a broadcast not restart on a new call. Rather, it waits for it to finish
> 
> 
> 
> Wait really? Can I know what the it is?
> 
> 

Wdym what the it is.

**Comment by YogaindoCR** [comment]
> Wdym what the it is.

Pardon for my quick texting lol, I just found what it is! Thank you!
