### ISSUE TITLE
sprite effects just does not work on IOS devices

### ISSUE THREAD

**Issue by GamerX9999** [SharkPool-SP/SharkPools-Extensions#107]
https://github.com/user-attachments/assets/0d801c77-b5ab-492d-9147-15e6d0ef0dae

for some reason sprite effects won’t work on IOS devices, works fine with Android, i’m just wondering if there’s a way to fix this.

**Comment by SharkPool-SP** [comment]
Can't fix. It's an issue with Safari. Safari is just a bad browser
