### ISSUE TITLE
[Animations] Animations overlap when played at the same time + option to force an animation

### ISSUE THREAD

**Issue by gomiigg** [SharkPool-SP/SharkPools-Extensions#108]
I cannot record a video demonstration right now, but I have provided a sample project with the following directions.

I am testing implementation for an animation system using Sparrow v2 Texture Atlases and the Animations extension.
However, when an animation is playing, starting another one does not stop the last played animation. The sprite begins to flicker between both animations.

In the project file, simply press 'R' to begin a long animation. Then press 'SPACE' in between, and notic the flickering.
A possible workaround is to make a custom 'Force Animation ()' block that stops all existing animations before playing the new animation, but I feel like this should just have native support right in the extension.

[SparrowAtlas.zip](https://github.com/user-attachments/files/17551542/SparrowAtlas.zip)

**Comment by SharkPool-SP** [comment]
couldnt you just stop all other animations

**Comment by SharkPool-SP** [comment]
Rewrote the extension. Its now faster and should fix that delay issue
