### ISSUE TITLE
Sprite Effects/TurboSkins messing with sprites

### ISSUE THREAD

**Issue by MrNooberDude** [SharkPool-SP/SharkPools-Extensions#110]
Here's a little video:

https://github.com/user-attachments/assets/8e4c9377-498d-41cf-a41c-de6897a37500

Basically, the problem I'm having is that one of the extensions is screwing up the sprite's rendering somehow. I'm not going to pretend I know how this works considering you've had much more experience with the PM internals and your own extensions (plus, I don't know JS)

**Comment by SharkPool-SP** [comment]
Not a bug. It's just a stupid way the renderer works. To fix it you need to use the set rotation center block

**Comment by SharkPool-SP** [comment]
> Is there an easy way to fix it using the rotation center since manually entering values for 50+ uncentered sprites is inconvenient 

You can use looks+ to get the original rotation center of the costume
