### ISSUE TITLE
Unable to add extenion through file and text

### ISSUE THREAD

**Issue by Ronxlotl** [SharkPool-SP/SharkPools-Extensions#111]
I tried adding Variable Expanded extenion through file but it gave me an error and I tried to add Variable Expanded tgrough text but it gave me the same error.

![Screenshot 2024-11-29 110015](https://github.com/user-attachments/assets/5309170a-76d5-46de-9d02-4bdf468494b8)

**Comment by SharkPool-SP** [comment]
> I tried adding Variable Expanded extenion through file but it gave me an error and I tried to add Variable Expanded tgrough text but it gave me the same error.
> 
> 
> 
> ![Screenshot 2024-11-29 110015](https://github.com/user-attachments/assets/5309170a-76d5-46de-9d02-4bdf468494b8)
> 
> 

You're loading the extension with the sandbox on. You're supposed to load extensions from my gallery "without sandbox"
