### ISSUE TITLE
More than a issue a question

### ISSUE THREAD

**Issue by Efrainett** [SharkPool-SP/SharkPools-Extensions#112]
Hi, I would like to ask about the “Sprite Effects” extension and I have already tried to use the “Skins” and “Looks+” extension to show the SVG generated by the extension but one problem is that when I try to load for example the Blur, Outline or another effect, the effect is cut and applied only in the width and height of the sprite so I would like to know the correct way to use it or if there is a limitation, thanks.

Here's how it ends up looking.

![image](https://github.com/user-attachments/assets/1790e2db-d7cc-4863-a7a6-6c23b6ec26d5)

This is how I use the blocks to display the generated SVG.

![block_11_12_2024-07_40_59](https://github.com/user-attachments/assets/a10c9091-30f6-4e2d-8a55-0b655eb3e11b)
![block_11_12_2024-07_40_53](https://github.com/user-attachments/assets/f131ad09-acb4-4ee3-b0f5-b69610110709)

**Comment by Efrainett** [comment]
My apologies, after this I realized that there is another problem that is the same as mine X'D

**Comment by SharkPool-SP** [comment]
Either add a invisible box to the costume, or use the expand viewbox block combined with the others

**Comment by Efrainett** [comment]
Okay thanks :D

**Comment by SharkPool-SP** [comment]
> > Either add a invisible box to the costume, or use the expand viewbox block combined with the others
> 
> where is expand viewbox block tho?

right below the masking blocks

<img width="253" alt="Image" src="https://github.com/user-attachments/assets/6869bf88-e342-4980-a27d-6f790dd70c6d" />
