### ISSUE TITLE
Variables Extended Loading Issue

### ISSUE THREAD

**Issue by MilkWithCereal** [SharkPool-SP/SharkPools-Extensions#21]
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/83046401/b6914915-577e-43aa-9e87-09b76e05a235)
This makes projects unable to load. 
could you please try to at least archive the link somewhere? 
it could definetly have projects work again

**Comment by SurvExe1Pc** [comment]
you have to load it via text so copy and paste it.

**Comment by SharkPool-SP** [comment]
> ![image](https://user-images.githubusercontent.com/83046401/280477063-b6914915-577e-43aa-9e87-09b76e05a235.png) This makes projects unable to load. could you please try to at least archive the link somewhere? it could definetly have projects work again

Should be fixed now!

**Comment by SurvExe1Pc** [comment]
j
