### ISSUE TITLE
Niche Toolbox Full Version Would Not Load

### ISSUE THREAD

**Issue by liam2736** [SharkPool-SP/SharkPools-Extensions#28]
On Penguin Mod, I would go to the unsafe extension gallery, copy the link for Niche Toolbox, paste the link into my browser,
copy the code, paste it into Penguin Mod, load it without the sandbox, and it won't show up.

**Comment by SharkPool-SP** [comment]
> On Penguin Mod, I would go to the unsafe extension gallery, copy the link for Niche Toolbox, paste the link into my browser, copy the code, paste it into Penguin Mod, load it without the sandbox, and it won't show up.

Same thing with me, idk why it happens, but its out of my control. Contact the creator of the extension

**Comment by SurvExe1Pc** [comment]
its intentional to say the least
