### ISSUE TITLE
Recording Extension: Suggestion, bugs and ideas

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#30]
This extension has a big potential. We can create in-game voice with this extension
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/f7711995-72de-4720-a21e-da30a8baac64)
Since Turbowarp Cloud Can send up to 100000 data, I see that this is a big win

But then I noticed, when we turned on the mic, it needed a time to turn it on. This is bad for a realtime conversation, cuz it's cut the audio.

I really hope that there is a block where we can extract the audio data without stopping the recording
Also I noticed that my CPU goes up overtime, Fix this :^

**Comment by SharkPool-SP** [comment]
> This extension has a big potential. We can create in-game voice with this extension
> 
> ![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/f7711995-72de-4720-a21e-da30a8baac64)
> 
> Since Turbowarp Cloud Can send up to 100000 data, I see that this is a big win
> 
> 
> 
> But then I noticed, when we turned on the mic, it needed a time to turn it on. This is bad for a realtime conversation, cuz it's cut the audio.
> 
> 
> 
> I really hope that there is a block where we can extract the audio data without stopping the recording
> 
> Also I noticed that my CPU goes up overtime, Fix this :^
> 
> I'll look into live extraction. For the cpu issue, does it go up when the mic is on? If so, does the cpu go down after you clear the recording?

Side note with that image. Don't use numerical encoding, the encoded strings are longer than it should be.
Excuse the self advertisement but use Sharktilities, there's a cloud encode/decode block which encodes strings. It is 2x shorter than Numerical Encoding

**Comment by YogaindoCR** [comment]
> I'll look into live extraction. For the cpu issue, does it go up when the mic is on? If so, does the cpu go down after you clear the recording?

Nice! Also the cpu goes up after we turn on and off the mic in a forever loop like this:
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/81210a1d-8eaf-4c44-bcd4-ea99e371eef5)
After running it:
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/dd2c2650-8cb6-4f0b-b236-4881c960e2a8)

**Comment by SharkPool-SP** [comment]
> > I'll look into live extraction. For the cpu issue, does it go up when the mic is on? If so, does the cpu go down after you clear the recording?
> 
> Nice! Also the cpu goes up after we turn on and off the mic in a forever loop like this: ![image](https://private-user-images.githubusercontent.com/132117105/298245236-81210a1d-8eaf-4c44-bcd4-ea99e371eef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1MjM2LTgxMjEwYTFkLThlYWYtNGM0NC1iY2Q0LWVhOTllMzcxZWVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGZkZTk4ZmM4ZTAzMzE0ODhlM2Y3ZGJkNjM0ZjI1MWIzNDRkNTY4YmVhNjNlODIyYjNiNTk2MGYzZGEzNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_3Frk1muuFIcInIvKJqbWIrIlaHvA_H6RHKhBclhSk) After running it: ![image](https://private-user-images.githubusercontent.com/132117105/298245389-dd2c2650-8cb6-4f0b-b236-4881c960e2a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1Mzg5LWRkMmMyNjUwLThjYjYtNGYwYi1iMjM2LTQ4ODFjOTYwZTJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWYwOTIxOGVhMTVlOWFjNjMzOTZkZjFiODQ3MTIyNTVlYWFjMTgyMDRiNWRlY2VmNzJiYzM4ZGRlMGE2MjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2QzWSLvsPUwcOB8pkKd7Xmviba3yzB8rKRXGohqXIxE)
> 
> Anyway I just checked your utilites and it was great

ah, it goes up cuz ur constantly turning it on and off. Ofc.... it needs to set up that. Might be able to change it idk. Also, you dont need to enable and disable the mic when you have the record for x seconds block. Since it turns it on/off

**Comment by YogaindoCR** [comment]
> > > I'll look into live extraction. For the cpu issue, does it go up when the mic is on? If so, does the cpu go down after you clear the recording?
> > 
> > 
> > Nice! Also the cpu goes up after we turn on and off the mic in a forever loop like this: ![image](https://private-user-images.githubusercontent.com/132117105/298245236-81210a1d-8eaf-4c44-bcd4-ea99e371eef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1MjM2LTgxMjEwYTFkLThlYWYtNGM0NC1iY2Q0LWVhOTllMzcxZWVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGZkZTk4ZmM4ZTAzMzE0ODhlM2Y3ZGJkNjM0ZjI1MWIzNDRkNTY4YmVhNjNlODIyYjNiNTk2MGYzZGEzNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_3Frk1muuFIcInIvKJqbWIrIlaHvA_H6RHKhBclhSk) After running it: ![image](https://private-user-images.githubusercontent.com/132117105/298245389-dd2c2650-8cb6-4f0b-b236-4881c960e2a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1Mzg5LWRkMmMyNjUwLThjYjYtNGYwYi1iMjM2LTQ4ODFjOTYwZTJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWYwOTIxOGVhMTVlOWFjNjMzOTZkZjFiODQ3MTIyNTVlYWFjMTgyMDRiNWRlY2VmNzJiYzM4ZGRlMGE2MjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2QzWSLvsPUwcOB8pkKd7Xmviba3yzB8rKRXGohqXIxE)
> > Anyway I just checked your utilites and it was great
> 
> ah, it goes up cuz ur constantly turning it on and off. Ofc.... it needs to set up that. Might be able to change it idk. Also, you dont need to enable and disable the mic when you have the record for x seconds block. Since it turns it on/off

Ahh I see... By the way the cpu stayed on high even I turned it off and completely remove the mic script, you might need to look into it.

Anyway I hope the live extraction idea works, Imagine making a online game with a in-game voice in it that would be so much fun xd

**Comment by SharkPool-SP** [comment]
> > > > I'll look into live extraction. For the cpu issue, does it go up when the mic is on? If so, does the cpu go down after you clear the recording?
> > > 
> > > 
> > > Nice! Also the cpu goes up after we turn on and off the mic in a forever loop like this: ![image](https://private-user-images.githubusercontent.com/132117105/298245236-81210a1d-8eaf-4c44-bcd4-ea99e371eef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1MjM2LTgxMjEwYTFkLThlYWYtNGM0NC1iY2Q0LWVhOTllMzcxZWVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGZkZTk4ZmM4ZTAzMzE0ODhlM2Y3ZGJkNjM0ZjI1MWIzNDRkNTY4YmVhNjNlODIyYjNiNTk2MGYzZGEzNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_3Frk1muuFIcInIvKJqbWIrIlaHvA_H6RHKhBclhSk) After running it: ![image](https://private-user-images.githubusercontent.com/132117105/298245389-dd2c2650-8cb6-4f0b-b236-4881c960e2a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MjAzNTUsIm5iZiI6MTcwNTcyMDA1NSwicGF0aCI6Ii8xMzIxMTcxMDUvMjk4MjQ1Mzg5LWRkMmMyNjUwLThjYjYtNGYwYi1iMjM2LTQ4ODFjOTYwZTJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwMzA3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWYwOTIxOGVhMTVlOWFjNjMzOTZkZjFiODQ3MTIyNTVlYWFjMTgyMDRiNWRlY2VmNzJiYzM4ZGRlMGE2MjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2QzWSLvsPUwcOB8pkKd7Xmviba3yzB8rKRXGohqXIxE)
> > > Anyway I just checked your utilites and it was great
> > 
> > 
> > ah, it goes up cuz ur constantly turning it on and off. Ofc.... it needs to set up that. Might be able to change it idk. Also, you dont need to enable and disable the mic when you have the record for x seconds block. Since it turns it on/off
> 
> Ahh I see... By the way the cpu stayed on high even I turned it off and completely remove the mic script, you might need to look into it.
> 
> Anyway I hope the live extraction idea works, Imagine making a online game with a in-game voice in it that would be so much fun xd

workin on it rn. It wont be as you expect, I need to make a new block for it. However, I dont seem to get any cpu problems? I believe its due to constantly turning on/off the mic and storing large audio recordings. The coming update should fix that. If not, get a better computer idk 🤷‍♂️

**Comment by SharkPool-SP** [comment]
Didnt work, I wasted an entire day on fixing something I cant do. I updated it with some new stuff that might come in handy. Also changed some stuff so old recordings arent deleted when recording
