### ISSUE TITLE
Better Input Buttons?

### ISSUE THREAD

**Issue by Coke-Unity** [SharkPool-SP/SharkPools-Extensions#31]
How do I use the Buttons thing in the Better Input extension? or am I just missing something obvious?

**Comment by SharkPool-SP** [comment]
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/139097378/6283cb2a-8f5d-4094-bd7c-2b1684a93b25)
Use these buttons in formatting. They create/delete buttons. 

The changed button layout shows on the next input box. Visual changes to those buttons are found in the visuals section in the menu. The new buttons will show up in the menu.

**Comment by Coke-Unity** [comment]
Yes but how do I make the buttons do things? I think you forgot that part

**Comment by SharkPool-SP** [comment]
> Yes but how do I make the buttons do things? I think you forgot that part

wdym "do things". Currently they close the box (unless its the dropdown button)

**Comment by SharkPool-SP** [comment]
@Coke-Unity

**Comment by Coke-Unity** [comment]
I want to have a text box and have a bunch of buttons that decide what to do with that text input but I can't because the buttons only close the prompt and continue with my code. also sorry for my late response.

**Comment by SharkPool-SP** [comment]
> I want to have a text box and have a bunch of buttons that decide what to do with that text input but I can't because the buttons only close the prompt and continue with my code. also sorry for my late response.

I dont plan on making buttons not close the textbox. This is for numerous reasons that are hard to explain. However, I suggest you open another text box when a answer is submitted for the first. If you want to detect which button was pressed, theres no way to do it as of V3.1. Dont worry though, Im working on Better Input V4 with a lot of new features, including:
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/139097378/c2dd0ba4-e345-4374-ab52-1ef7b1f1ef01)

**Comment by Coke-Unity** [comment]
YES THANK YOU FOR THIS! (Again sorry for the late Response I am in school lol)

**Comment by SharkPool-SP** [comment]
> YES THANK YOU FOR THIS! (Again sorry for the late Response I am in school lol)

Np, for now use that method. Idk when exactly v4 will release, so for now you have to a find a workaround.

I will say the v4 is close

**Comment by SharkPool-SP** [comment]
> YES THANK YOU FOR THIS! (Again sorry for the late Response I am in school lol)

btw in Better Input V4 a bug I am deciding to keep in a "bug" labeled as a feature that stops allowing Textboxes to close on button click.

**Comment by SharkPool-SP** [comment]
@Coke-Unity Better Input V4 IS OUT!
Enjoy :)

You can close this issue now

**Comment by SharkPool-SP** [comment]
> Thank you for this!!!

No problem
