### ISSUE TITLE
the site wont work and idk why

### ISSUE THREAD

**Issue by polygoners1** [SharkPool-SP/SharkPools-Extensions#33]
a have proof!
[broken site.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/149721398/e6deaab7-f386-4974-bb25-d14712eda2c4)
sorry for low FPS its just the screen recording being bad.

**Comment by SharkPool-SP** [comment]
> a have proof! [broken site.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/149721398/e6deaab7-f386-4974-bb25-d14712eda2c4) sorry for low FPS its just the screen recording being bad.

your internet might be blocking the assets. Whats ur device and broswer

**Comment by Ashimee** [comment]
try opening an asset in a new tab

**Comment by polygoners1** [comment]
> > a have proof! [broken site.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/149721398/e6deaab7-f386-4974-bb25-d14712eda2c4) sorry for low FPS its just the screen recording being bad.
> 
> your internet might be blocking the assets. Whats ur device and browser

default chrome OS v103.0.5060.132 (Official Build) (64-bit). idk how to view my device model but its a 2019 ASUS chromebook.

**Comment by polygoners1** [comment]
oops i was looking at the ways for completing a issue. its not done BTW

**Comment by SharkPool-SP** [comment]
> oops i was looking at the ways for completing a issue. its not done BTW

Did you do what Ashime said

**Comment by polygoners1** [comment]
> > oops i was looking at the ways for completing a issue. its not done BTW
> 
> Did you do what Ashime said

yes, and it opened with no problem (the asset did.)

**Comment by SharkPool-SP** [comment]
> > > oops i was looking at the ways for completing a issue. its not done BTW
> 
> > 
> 
> > Did you do what Ashime said
> 
> 
> 
> yes, and it opened with no problem (the asset did.)

Try the GitHub link

**Comment by polygoners1** [comment]
> > > > oops i was looking at the ways for completing a issue. its not done BTW
> > 
> > 
> > > 
> > 
> > 
> > > Did you do what Ashime said
> > 
> > 
> > yes, and it opened with no problem (the asset did.)
> 
> Try the GitHub link
> 
> https://sharkpool-sp.github.io/SharkPools-Extensions/

idk how but it was the one from the vid and now : [WAIT NOW IT WORKS!.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/149721398/e8a0faa5-970c-4f00-ab46-3e27b4338f7f)

**Comment by polygoners1** [comment]
wait the pm route still dont work

**Comment by SharkPool-SP** [comment]
> wait the pm route still dont work

Yes. So the problem can't be solved on my side. Your internet blocks vercel. So only the GitHub link works for you. 

Penguinmod uses the vercel link, so can't rlly do anything abt it 🤷‍♂️

**Comment by polygoners1** [comment]
oh yeah, i should have given a backstory. so, the site worked before, but when i tried to use tuneshark to see if i could change the audio quality, that happened. i mean, at least i can use it by downloading 50000 javascript files instead of copying the link.

**Comment by SharkPool-SP** [comment]
> oh yeah, i should have given a backstory. so, the site worked before, but when i tried to use tuneshark to see if i could change the audio quality, that happened. i mean, at least i can use it by downloading 50000 javascript files instead of copying the link.

Most likely your internet caught on that you visited the sight too many times, and since it's a bit unknown it blocked it. Idk
