### ISSUE TITLE
Smooth Bloom Effect

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#39]
I noticed that the bloom effect in the _**Sprite effect extension**_ are blocky
So i did some research and here what I found:

>Before
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/453d8640-9af0-4a4b-95f0-391072e2bc6f)

>After
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/132117105/71097088-e60a-45d3-a1fb-7f39ccb1054c)

So all I did is added this simple code to the _feblend in 2_
_color-interpolation-filters="sRGB"_

Example:
_<feColorMatrix in1="SourceGraphic" type="matrix" values=""></feColorMatrix><feBlend in2="SourceGraphic" mode="screen" **color-interpolation-filters="sRGB"** /></filter>_

**Comment by SharkPool-SP** [comment]
If you make this a pull request I’ll merge it. Just add yourself to contributors. Thanks for the help tho :))))

glad you like Sprite Effects

**Comment by YogaindoCR** [comment]
> If you make this a pull request I’ll merge it. Just add yourself to contributors. Thanks for the help tho :))))
> 
> glad you like Sprite Effects

Ahh alright :>

**Comment by SharkPool-SP** [comment]
Added
