### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by Quartonos** [SharkPool-SP/SharkPools-Extensions#40]
Hello! can you make an Google Drive extension????

**Comment by SharkPool-SP** [comment]
> Hello! can you make an Google Drive extension????

cant sorry. Anything that has to do with google files is near impossible to do since google is very secure and protective :/

**Comment by SharkPool-SP** [comment]
> > Hello! can you make an Google Drive extension????
> 
> cant sorry. Anything that has to do with google files is near impossible to do since google is very secure and protective :/
