### ISSUE TITLE
Pause Utilities: Not Working on Packaged

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#41]
When I see the console it says
"Pause Button Not Found" Even after I turned on the button in the controls on the packager settings on TurboWarp

**Comment by SharkPool-SP** [comment]
> When I see the console it says
> 
> "Pause Button Not Found" Even after I turned on the button in the controls on the packager settings on TurboWarp

Oh. Garbomuffin might've changed the packager. I'll look into it.

**Comment by SharkPool-SP** [comment]
fixed
