### ISSUE TITLE
Youtube Operations glitch

### ISSUE THREAD

**Issue by ASTHEBEST** [SharkPool-SP/SharkPools-Extensions#43]
When you convert all videos into mp4s, it returns ess

**Comment by SharkPool-SP** [comment]
> When you convert all videos into mp4s, it returns ess

It returns what?

**Comment by SharkPool-SP** [comment]
It would also be nice to have an image or any other thing to show the issue

**Comment by SharkPool-SP** [comment]
Im closing this issue for now, until I get a response.

It doesnt happen to me.

**Comment by SharkPool-SP** [comment]
k, found how to replicate it. Will look into it

**Comment by SharkPool-SP** [comment]
Fixed!
