### ISSUE TITLE
Spreadsheets Extension Comma Messes with JSON

### ISSUE THREAD

**Issue by WyvurnYT** [SharkPool-SP/SharkPools-Extensions#47]
When you have a cell with a comma in it, it messed up the JSON result.
Expectation: 
![Screenshot 2024-03-13 173254](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/153701920/3bc0c065-e225-460d-8323-9df82e0a6bd5)

Reality:
[![Screenshot 2024-03-13 173244](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/153701920/82154d5f-efaa-4370-80be-01669aa79957)
](url)

**Comment by SharkPool-SP** [comment]
Fixed!
