### ISSUE TITLE
sharkpool site connection reset

### ISSUE THREAD

**Issue by samet9999** [SharkPool-SP/SharkPools-Extensions#54]
![Ekran görüntüsü 2024-03-27 171514](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/156913291/2702e007-8aec-4544-9426-bbb8fe362366)

error is Your connection to this site is not secure

**Comment by samet9999** [comment]
help please What can I do?!

**Comment by SharkPool-SP** [comment]
> ![Ekran görüntüsü 2024-03-27 171514](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/156913291/2702e007-8aec-4544-9426-bbb8fe362366)
> 
> 
> 
> error is Your connection to this site is not secure

Seems to be an internet issue on your side

**Comment by SharkPool-SP** [comment]
Use this link:

https://sharkpool-sp.github.io/SharkPools-Extensions/

**Comment by samet9999** [comment]
> Bu bağlantıyı kullanın:
> 
> https://sharkpool-sp.github.io/SharkPools-Extensions/

**Comment by samet9999** [comment]
> Bu durumda şunu kullanın:
> 
> https://sharkpool-sp.github.io/SharkPools-Extensions/

ok fixed
