### ISSUE TITLE
how is this done

### ISSUE THREAD

**Issue by LittleBlueGamer427** [SharkPool-SP/SharkPools-Extensions#55]
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/148423893/efc9ca95-0e21-46ff-91f7-47e62514ad4a)

**Comment by SharkPool-SP** [comment]
API for penguinmod, made by JeremyGamer

**Comment by LittleBlueGamer427** [comment]
where do i get it

**Comment by SharkPool-SP** [comment]
> where do i get it

should be in live tests

**Comment by LittleBlueGamer427** [comment]
> > where do i get it
> 
> should be in live tests

whats the name im having trouble finding

**Comment by LittleBlueGamer427** [comment]
> > > where do i get it
> > 
> > 
> > should be in live tests
> 
> whats the name im having trouble finding

(of the ext)

**Comment by SharkPool-SP** [comment]
> > > > where do i get it
> > > 
> > > 
> > > should be in live tests
> > 
> > 
> > whats the name im having trouble finding
> 
> (of the ext)

Test Extension Loader
