### ISSUE TITLE
PLEASE HELP ME SHARKPOOL🤏🙏🤝😍!!!

### ISSUE THREAD

**Issue by WAYLIVES** [SharkPool-SP/SharkPools-Extensions#56]
## I need a block with which you can change the background color. 🎨

> I know ShrkPools you are a very good programmer and you create very useful extensions for TurboWarp and PinguinMod. I'm not good at this, so I came to you for help. You can refuse, because you have every right to do so.

Please help me design one or more blocks (as you wish) so that we can change the background color?

**Comment by SharkPool-SP** [comment]
What

**Comment by WAYLIVES** [comment]
about this block:

![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/130656326/d78436d9-661a-4546-89af-e2062888746f)

**Comment by WAYLIVES** [comment]
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/130656326/6b15adda-57cb-4579-a31b-7b974169aeab)

**Comment by SharkPool-SP** [comment]
That exists in the camera extension in turbowarp, just look there

**Comment by WAYLIVES** [comment]
> That exists in the camera extension in turbowarp, just look there

OH!!! THANK YOU VERY MUTCH !!!
