### ISSUE TITLE
how does tile grid extension work and how to use it in games

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#59]

**Comment by SharkPool-SP** [comment]
Basically, you create grids and snap sprites to them. Useful for tile-based games

**Comment by hammouda101010** [comment]
can you make documentation with examples? i tried to make a grid system but it didn't work as expected

**Comment by SharkPool-SP** [comment]
> can you make documentation with examples? i tried to make a grid system but it didn't work as expected
I dont have time to write documentation for every extension, so its best just to do this anyways:
![image](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/139097378/3debcd9b-d047-430d-a4a9-aee6f57d9641)
Try this

**Comment by hammouda101010** [comment]
thanks that is very helpful!

**Comment by SharkPool-SP** [comment]
Np

**Comment by LittleBlueGamer427** [comment]
after placing sprite on grid you can change the position
