### ISSUE TITLE
BUG: the 2000 expanded extension shows -1 centuries since 2000

### ISSUE THREAD

**Issue by ASTHEBEST** [SharkPool-SP/SharkPools-Extensions#60]
the 2000 expanded extension shows -1 centuries since 2000, and idk if intentional but things like months since 2000 are rounded.

**Comment by SharkPool-SP** [comment]
I didn't make that extension, but I'll look into it and let you know if it's supposed to do that

**Comment by SharkPool-SP** [comment]
oh its literally just not coded in. Ill fix it and rewrite it entirely since its formatted poorly

**Comment by SharkPool-SP** [comment]
Fixed
