### ISSUE TITLE
permission to be included in Snail IDE's new gallery

### ISSUE THREAD

**Issue by dumorando** [SharkPool-SP/SharkPools-Extensions#61]
Snail ide has had some issues with "extension stealing" for a while so were revamping the extension system. The new extensions will be found at https://snail-ide.com/extensions and we need permission if we can fetch extensions from here.

**Comment by SharkPool-SP** [comment]
Sure. Make sure there's credit to me. You can also add a link to my gallery, you don't have to though

**Comment by dumorando** [comment]
thanks! we'll make sure to credit u
