### ISSUE TITLE
variables expanded checkbox issue

### ISSUE THREAD

**Issue by fo-od** [SharkPool-SP/SharkPools-Extensions#63]
how do you use it? i thought it would automatically set the variable to true or false based on the check, but it doesn't (idk if its a bug)

**Comment by fo-od** [comment]
actually it seems like no variables are being updated (color monitor, I choose a different color, doesn't update the variable)

**Comment by SharkPool-SP** [comment]
> actually it seems like no variables are being updated (color monitor, I choose a different color, doesn't update the variable)

its working for me? Can you send a video for proof/more info?

**Comment by fo-od** [comment]
[Screen recording 2024-05-03 9.41.49 PM.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/99752044/2b378114-7337-488a-a806-e5527944121d)

**Comment by fo-od** [comment]
im using the copied code from the github pages site if that changes anything, your vercel site is blocked for me (lightspeed categorizes it as a proxy)

if you need the pmp file I'm in the pm discord and I can make a post in the help channel

**Comment by SharkPool-SP** [comment]
It seems that only happens in the variables tab. Making a sprite say the value seems to work

**Comment by fo-od** [comment]
not only in the variables tab, does it being a local variable change anything? (I also tested making it say the variable and its the same result as the video)
[Screen recording 2024-05-03 10.42.10 PM.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/99752044/66f03b9d-4118-4051-8910-d6238fe2e806)

**Comment by fo-od** [comment]
it seems to be an issue with my project specifically???? i dont get why though

**Comment by fo-od** [comment]
im going to make a post in the pm discord and send the pmp file

**Comment by SharkPool-SP** [comment]
we discussed this on discord, concluded it not my ext being buggy.
