### ISSUE TITLE
many spaces does not render in text display extension

### ISSUE THREAD

**Issue by Ender-Studio** [SharkPool-SP/SharkPools-Extensions#68]
if u put 2+ space it only shows 1

**Comment by SharkPool-SP** [comment]
> if u put 2+ space it only shows 1

It's an html thing and can't be fixed. However you could use a special character that acts as a space and can be stacked, press
"Alt + 255"

**Comment by Ender-Studio** [comment]
oh if thats the case ill use replace all the space with that when it gets rendered but still space in the variable. is there a way to set a global setting for every text u would place like font and fontsize font color

**Comment by Ender-Studio** [comment]
also how to add lines
