### ISSUE TITLE
How did you get a turbowarp project hosted on github?

### ISSUE THREAD

**Issue by snowboyz0825** [SharkPool-SP/SharkPools-Extensions#71]
I have been trying to figure it out FOREVER, how did you do it?

**Comment by SharkPool-SP** [comment]
You package the project :trollface:

**Comment by snowboyz0825** [comment]
> You package the project :trollface:

Yea I figured it out using this repository lmao, the only thing that I didn't realize was that you have to rename it to index. I looked at your html and realized it was literally just a packaged project, so I renamed it and I got a demo site working. Womp womp lol

**Comment by SharkPool-SP** [comment]
ok

**Comment by LittleBlueGamer427** [comment]
you use vercel or github pages
