### ISSUE TITLE
Image Effect & Sprite Effects: Result Image is always centered?

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#73]
First of all the plugin is really great. It allow us to edit some effects for the sprites we want, And then centering it to reduce Image height and Width to process faster, but I think centering the image results is a bad idea?
Before
![image](https://github.com/user-attachments/assets/a130135e-ca66-40ca-a253-2b72c5bd1034)

After adding some little noise (She's looking kinda funky lol)
![image](https://github.com/user-attachments/assets/0b80b58f-4ac9-42d9-a4b6-7e399dfa0fb8)

Here the code I used
![image](https://github.com/user-attachments/assets/e3f44b64-ed6f-49fb-8a84-fbee0f312cd0)

Any thought or work-around for this?

**Comment by SharkPool-SP** [comment]
Oh the centering is not my extension. It's skins loading images. For some reason it auto centers. It is an issue Garbomuffin is trying to fix

**Comment by YogaindoCR** [comment]
Ahh interesting, I hope he fixed it real quick tho
