### ISSUE TITLE
Layer Control: support new layers added by other extensions

### ISSUE THREAD

**Issue by Xeltalliv** [SharkPool-SP/SharkPools-Extensions#76]
Some extensions add their own layers (e.g. [Simple3D](https://extensions.turbowarp.org/Xeltalliv/simple3D.js) (adds new drawable and new layer group), [CST's 3D](https://raw.githubusercontent.com/CST1229/turbowarp-extensions/3d/extensions/CST1229/3d.js) (adds new drawable to existing pen layer group)). The suggestion is to provide some way for other extensions to add more dropdown options to the first block and output values to the second block:
![image](https://github.com/user-attachments/assets/c870f0d8-8930-44ad-a47d-d05b3b2ef01b)

**Comment by SharkPool-SP** [comment]
Those extensions still rely on the drawable ID. So you can just input the number of the custom layer

**Comment by SharkPool-SP** [comment]
Custom layers are now supported, as discussed in Discord.
For anyone reading this in the future, to have a custom layer supported, add:
`customDrawableName` and the Extensions Layer Name to the Drawable :)
