### ISSUE TITLE
toggle bounds does not make certain UI unclickable

### ISSUE THREAD

**Issue by unknown07724** [SharkPool-SP/SharkPools-Extensions#77]
I tried it as an extension and nothing became unclickable not even stuff nearby the new button that was added

**Comment by unknown07724** [comment]
there is A weird bug where if you hide a sprite with borders on the borders expand a little bit

**Comment by SharkPool-SP** [comment]
> I tried it as an extension and nothing became unclickable not even stuff nearby the new button that was added

https://github.com/SharkPool-SP/SharkPools-Extensions/blob/main/Editor-Addons/Toggle-Bounds.js#L8C10-L8C15
Invalid Issue. In case it wasn't clear enough.
