### ISSUE TITLE
Extra Controls: Step Through Block Fails

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#82]
Step through block is not working in this custom blocks
It's continuing the block below but not canceling the blocks inside it
![image](https://github.com/user-attachments/assets/03448cb3-3c58-4c00-8bfe-c0c813acda70)

Inside the custom block function:
![image](https://github.com/user-attachments/assets/95161919-1b15-418a-968a-929c5fc96bda)

**Comment by SharkPool-SP** [comment]
Can you send the project

**Comment by SharkPool-SP** [comment]
Nevermind, figured out the problem.

I just fixed it, update the Extra Controls file :)

**Comment by YogaindoCR** [comment]
> Nevermind, figured out the problem.
> 
> I just fixed it, update the Extra Controls file :)

Nice!!!!

**Comment by YogaindoCR** [comment]
The Step Through block did not works when The compiler is disabled.
![image](https://github.com/user-attachments/assets/9749fab7-0ceb-4410-8c07-93af95af3c90)
I hope this fixed too

**Comment by SharkPool-SP** [comment]
now it should work :)
