### ISSUE TITLE
Better Input Not Working When Packaging Projects in Penguinmod #bug

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#83]

**Comment by SharkPool-SP** [comment]
can I get some more information? It seems to work fine for me

**Comment by hammouda101010** [comment]
this line of code doesnt work when packaging the project:
![block_8_19_2024-4_19_15 PM](https://github.com/user-attachments/assets/10c16cf6-9909-4654-9e25-3f960d515b15)

**Comment by SharkPool-SP** [comment]
can you send the project

**Comment by hammouda101010** [comment]
[project loader.zip](https://github.com/user-attachments/files/16666757/project.loader.zip)

**Comment by SharkPool-SP** [comment]
The issue is actually with these
<img width="284" alt="Screenshot 2024-08-19 at 4 21 50 PM" src="https://github.com/user-attachments/assets/41e4c38c-603d-4a19-ae48-570ebdc8f3be">

Theyre outputting nothing

**Comment by hammouda101010** [comment]
so i need to get the data url of these files for the image of the buttons or else it wont work

**Comment by SharkPool-SP** [comment]
thats the way you coded it, yes

**Comment by hammouda101010** [comment]
so how do i get the url of a sprite costume

**Comment by SharkPool-SP** [comment]
looks+ or runtime probably. Figure it out

**Comment by hammouda101010** [comment]
ok it work just disable "Remove raw asset data after loading to save RAM" checkbox
