### ISSUE TITLE
Sprite Effects: Custom Canvas Filter Doesn't work in the latest updates

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#84]
I was made my own custom filter block for my game, but all of it suddenly stopped working
![image](https://github.com/user-attachments/assets/239f7063-9052-4918-9033-f7b937e5a743)
Is there any changes that you made to the filters?

**Comment by SharkPool-SP** [comment]
Yes, Garbomuffin requested custom filters applied on the canvas must be DOMpurified. 

So what you're putting on the canvas is being seen as dangerous to DOMpurify

**Comment by YogaindoCR** [comment]
Oh well, how can I fix it? Or maybe, you had the last version where it doesnt had dom verifier

**Comment by SharkPool-SP** [comment]
You could just mod the file to remove the DOM purify part

**Comment by SharkPool-SP** [comment]
Basically just always return the string in:

https://github.com/SharkPool-SP/SharkPools-Extensions/blob/main/extension-code/Sprite-Effects.js#L29C1-L43C4

**Comment by YogaindoCR** [comment]
Interesting
How can we bypasses this without using the Spriteeffect blocks?
Doesn't this removed our ability to create our own custom filters?
Or I just missed something
