### ISSUE TITLE
Text Display Positioning Now Working When Using in For a Second New ID.

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#85]

**Comment by SharkPool-SP** [comment]
> 

What?

**Comment by hammouda101010** [comment]
When Using Set Position of ID () at X:() Y:() with a Second id, It Sets it in an Another Position. and Not The Exact Position.

**Comment by SharkPool-SP** [comment]
> When Using Set Position of ID () at X:() Y:() with a Second id, It Sets it in an Another Position. and Not The Exact Position.

It's because of text margins and/or text alignment.

Turn on debug mode and you'll see the text box outline 👍

**Comment by hammouda101010** [comment]
fix your text margins thats the problem

**Comment by SharkPool-SP** [comment]
> fix your text margins thats the problem

There's literally a set margins block, **you** are supposed to set them
