### ISSUE TITLE
Extra Control: Step through block fail (again x3)

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#86]
A small issue when using step throught block
![image](https://github.com/user-attachments/assets/e2a0b80d-5e98-4f65-90df-144df7293975)
If it's inside a Forever block and it's got updated with the same as the While block, the block will just re run again

It can be fixed with adding a frame delay to give the Function a time to react:
![image](https://github.com/user-attachments/assets/681dee08-e754-4e0c-909e-77dd252e2b1a)

( Anyway I accidentaly drop my books on my keyboard and wrote F and enter... What a funny scenario :u )

**Comment by SharkPool-SP** [comment]
Ah I might know why

**Comment by SharkPool-SP** [comment]
fixed!
