### ISSUE TITLE
How to Add Multiple Textboxes at once with Better Input?

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#87]

**Comment by hammouda101010** [comment]
no the 2 boxes doesnt show up.

**Comment by SharkPool-SP** [comment]
> no the 2 boxes doesnt show up.

They overlap

**Comment by hammouda101010** [comment]
so how to not make then overlap

**Comment by SharkPool-SP** [comment]
Preset position block

**Comment by hammouda101010** [comment]
program only says there is one textbox i have no idea how this max box count even work 😭

**Comment by SharkPool-SP** [comment]
Set the max box count to 2 or more
Ask and wait, then use another ask and wait block
