### ISSUE TITLE
Extra Control: Loop Index Not Detecting Loops

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#88]
It's not working in both Compiler and disable compier
![image](https://github.com/user-attachments/assets/5969014f-364b-49f6-abf1-2ad42c80322f)
Note:
- The Sprites has clones
- There is griffpatch broadcast lag fix ( Tick Broadcast )
- The Project is Huge
- There is a Instant block running inside the Tick Broadcast and has "Repeat Until" in it

I've been reporting so many bugs with ur extension lately eh-
Your plugins is awesome :D

**Comment by SharkPool-SP** [comment]
Not a Bug:
in the Image you show this
<img width="90" alt="Screenshot 2024-08-26 at 1 47 50 AM" src="https://github.com/user-attachments/assets/5d0e72c5-85be-4c4b-9d65-aa16d68d851c">
solely on its own. This block will say the loop count from within the script it is in.

This means it will report different numbers when in different scripts.

Additionally, this block will **not** nor cannot detect loops outside the script (which includes message loops)

**Comment by SharkPool-SP** [comment]
also thanks for the support :D

**Comment by YogaindoCR** [comment]
Well I hope that's the case but...
![image](https://github.com/user-attachments/assets/25622457-3ede-4895-b2f1-3352f66fcd68)
![image](https://github.com/user-attachments/assets/4059a012-f543-4b9b-89f5-9731ea1dd582)

It's says 1 even thought it runs the next cycles


> > It's not working in both Compiler and disable compier ![image](https://private-user-images.githubusercontent.com/132117105/361369109-5969014f-364b-49f6-abf1-2ad42c80322f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjI0OTIsIm5iZiI6MTcyNDY2MjE5MiwicGF0aCI6Ii8xMzIxMTcxMDUvMzYxMzY5MTA5LTU5NjkwMTRmLTM2NGItNDlmNi1hYmYxLTJhZDQyYzgwMzIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwODQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDQ1NGVlYzNlOTQ5NzQwMDJlZTliOWYwNzEwODRkMWNlZDYwYmI5ODJkNjE1NGQ4NWU3NzBmNWE2ODkwYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tUQ19-OhA7o8YvPCZ_eWe_ZsXPpHH_B3PyQf0zC0lc4) Note:
> > 
> > * The Sprites has clones
> > * There is griffpatch broadcast lag fix ( Tick Broadcast )
> > * The Project is Huge
> > * There is a Instant block running inside the Tick Broadcast and has "Repeat Until" in it
> > 
> > I've been reporting so many bugs with ur extension lately eh- Your plugins is awesome :D
> 
> in the case of this script, the reason it the block inside the when I receive always returns 1 (if im understanding correctly) is because from what I can tell, the when I receive script has no time to fully complete when the next broadcast is sent

**Comment by YogaindoCR** [comment]
> Well I hope that's the case but... ![image](https://private-user-images.githubusercontent.com/132117105/361376766-25622457-3ede-4895-b2f1-3352f66fcd68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjMxNzcsIm5iZiI6MTcyNDY2Mjg3NywicGF0aCI6Ii8xMzIxMTcxMDUvMzYxMzc2NzY2LTI1NjIyNDU3LTNlZGUtNDg5NS1iMmYxLTMzNTJmNjZmY2Q2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwOTAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWEzZmNmOWU3NDI0MDY1ZGRiOWJlNzRmNmIzODU3N2MyOWIwOWM4YjUwMGM2ZTc1MzA3MjhhYWQzNzllYzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SHDb9mZFTNUfOLkYngDuR4OnYD0Z3EQE2UH6P0wpDIA) ![image](https://private-user-images.githubusercontent.com/132117105/361376815-4059a012-f543-4b9b-89f5-9731ea1dd582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjMxNzcsIm5iZiI6MTcyNDY2Mjg3NywicGF0aCI6Ii8xMzIxMTcxMDUvMzYxMzc2ODE1LTQwNTlhMDEyLWY1NDMtNGI5Yi04OWY1LTk3MzFlYTFkZDU4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwOTAxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2I2YWE4ODc2NWU2ZWZkMWRlYTYxOTNiMjlmMGM2NzZmMTkxNGFhODIyMDQ3MWE0YjVlZDY5ZDgzZTk0YjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ezdGNCeqcaKo_pBlGr-Wc52CbDIvfeT2AlHC2ZFEBBo)
> 
> It's says 1 even thought it runs the next cycles
> 
> > > It's not working in both Compiler and disable compier ![image](https://private-user-images.githubusercontent.com/132117105/361369109-5969014f-364b-49f6-abf1-2ad42c80322f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjI0OTIsIm5iZiI6MTcyNDY2MjE5MiwicGF0aCI6Ii8xMzIxMTcxMDUvMzYxMzY5MTA5LTU5NjkwMTRmLTM2NGItNDlmNi1hYmYxLTJhZDQyYzgwMzIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwODQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDQ1NGVlYzNlOTQ5NzQwMDJlZTliOWYwNzEwODRkMWNlZDYwYmI5ODJkNjE1NGQ4NWU3NzBmNWE2ODkwYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tUQ19-OhA7o8YvPCZ_eWe_ZsXPpHH_B3PyQf0zC0lc4) Note:
> > > 
> > > * The Sprites has clones
> > > * There is griffpatch broadcast lag fix ( Tick Broadcast )
> > > * The Project is Huge
> > > * There is a Instant block running inside the Tick Broadcast and has "Repeat Until" in it
> > > 
> > > I've been reporting so many bugs with ur extension lately eh- Your plugins is awesome :D
> > 
> > 
> > in the case of this script, the reason it the block inside the when I receive always returns 1 (if im understanding correctly) is because from what I can tell, the when I receive script has no time to fully complete when the next broadcast is sent

Also The tick broadcast I mean is on different scripts

**Comment by SharkPool-SP** [comment]
it does *not* actually run the next cycle.
Heres a example:
<img width="411" alt="Screenshot 2024-08-26 at 2 15 14 AM" src="https://github.com/user-attachments/assets/b3d9352e-e2cc-404d-a883-497a1bde4066">

**Comment by SharkPool-SP** [comment]
Heres a solution:
<img width="411" alt="Screenshot 2024-08-26 at 2 16 28 AM" src="https://github.com/user-attachments/assets/6b841e88-af4a-4c07-9ccf-7ea73fb475f9">

Another solution would be to run it in a new thread

**Comment by YogaindoCR** [comment]
![image](https://github.com/user-attachments/assets/c3e5bdc6-d855-486c-95e3-419d29adad97)
I just fixed it by restarting the project, This could be a red flag for a temporary bug

**Comment by YogaindoCR** [comment]
Anyway... I got other problems with ur extensions:
https://github.com/TurboWarp/desktop/issues/1057#issue-2486586540

**Comment by SharkPool-SP** [comment]
Yes, that's my fault, I'll fix in a bit

**Comment by SharkPool-SP** [comment]
Fixed

**Comment by YogaindoCR** [comment]
> Fixed

Thank you for your hard work!

**Comment by SharkPool-SP** [comment]
> > Fixed
> 
> 
> 
> Thank you for your hard work!

Np!
