### ISSUE TITLE
text dispayed x positions by text display is altered with fullscreen

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#89]

**Comment by hammouda101010** [comment]
before fullscreen:
![Screenshot 2024-08-28 201515](https://github.com/user-attachments/assets/37d9fbef-e3aa-4a93-8750-cb0b372f2504)
after fullscreen:
![Screenshot 2024-08-28 201524](https://github.com/user-attachments/assets/dabab0c8-2f79-47d9-908c-1e937a97c769)

**Comment by SharkPool-SP** [comment]
Set margins

**Comment by hammouda101010** [comment]
it doesnt work neither

**Comment by SharkPool-SP** [comment]
> it doesnt work neither

Use debug mode

**Comment by hammouda101010** [comment]
it doesnt show anything wrong, not even the margins

**Comment by SharkPool-SP** [comment]
> it doesnt show anything wrong, not even the margins

Send project

**Comment by hammouda101010** [comment]
[silly.zip](https://github.com/user-attachments/files/16790405/silly.zip)

**Comment by SharkPool-SP** [comment]
after further testing, I have 0 idea whats going on, nor do I have a fix. I highly believe the issue lies in your code since I saw no problems when opening a new project with display text and positioning text with & without fullscreen

**Comment by SharkPool-SP** [comment]
oh wait scratch that, found the issue :trollface: 

The issue is literally your margins.
Half the time you arent setting them and the other half you are setting them AFTER positioning. You should always set them before positioning

**Comment by hammouda101010** [comment]
yeah i HATE text margins. they killed my wife and family.

**Comment by SharkPool-SP** [comment]
![image](https://github.com/user-attachments/assets/5a32cd52-847e-4b01-b6a1-1457a2fb7fd0)
