### ISSUE TITLE
The Video extension doesn't work on iPhone when packaged with Turbowarp.

### ISSUE THREAD

**Issue by nickwong168** [SharkPool-SP/SharkPools-Extensions#92]
I was testing the Video extension and found the packaged iPhone problem. It works perfectly at editor, and also works fine on Android when packaged. But does't work on iPhone.

Here are the only blocks I'm using(and only one sprite for now):
![block_2024_9_5-16_51_50](https://github.com/user-attachments/assets/d62bf927-c923-492d-9adc-c6a793230822)

The URL of the video is https://newtousa.club/RRL/sample.mp4 (only 1.3MB)

I'm using the newest version of Turbowarp and add the Video extension from the official extension library.

All the package options are left default. And I've put the generated HTML file here: https://newtousa.club/RRL/a.html

Is there anything I did incorrectly? Thanks!

**Comment by SharkPool-SP** [comment]
Not my extension, can't help you there. Make an issue in the turbowarp repository

**Comment by nickwong168** [comment]
> Not my extension, can't help you there. Make an issue in the turbowarp repository

OK! But I can find your contribution information in the source code:
// Name: Video
// ID: lmsVideo
// Description: Play videos from URLs.
// By: LilyMakesThings <https://scratch.mit.edu/users/LilyMakesThings/>
**// By: SharkPool**
// License: MIT AND LGPL-3.0

If I have any misunderstanding, please forgive me.

**Comment by SharkPool-SP** [comment]
I contributed yes, but that doesn't mean I made the entire extension
