### ISSUE TITLE
Add "Download all" option

### ISSUE THREAD

**Issue by snowboyz0825** [SharkPool-SP/SharkPools-Extensions#93]
It would be helpful to have a download all button that downloads them all as a zip file. Also possibly a checklist option to decide what to download

**Comment by SharkPool-SP** [comment]
That idea has been passed around a lot, but overall it's a no.

Simply cause the it's either unstable or it can be worked around by just clicking other extensions. Additionally, if you want a download all button, you could just download the extension-code folder

**Comment by snowboyz0825** [comment]
It would be easy just to have it fetch every extension and add it directly to the zip extension, no?

**Comment by SharkPool-SP** [comment]
Eh, I don't see a point in that though

**Comment by snowboyz0825** [comment]
You cool if I make a PR after I have a try at adding it?

![Screenshot 2024-09-11 10 49 55 AM](https://github.com/user-attachments/assets/1c3f118b-b7c3-4295-897c-5dc120dc3a7d)
