### ISSUE TITLE
Add "Mouse Connected" block to Hypersense

### ISSUE THREAD

**Issue by snowboyz0825** [SharkPool-SP/SharkPools-Extensions#94]
If you use a toucpad and the scroll velocity block it works great, but if you try something optimized for a mouse with a touchpad it is far too sensitive. We should add a block to detect when a mouse is connected/used or a touchpad so we can accommodate properly

**Comment by SharkPool-SP** [comment]
> If you use a toucpad and the scroll velocity block it works great, but if you try something optimized for a mouse with a touchpad it is far too sensitive. We should add a block to detect when a mouse is connected/used or a touchpad so we can accommodate properly

Wdym

**Comment by snowboyz0825** [comment]
If you use a trackpad (like what's on a laptop) and scroll, the velocity isn't that much. If you use a mouse, then the scroll velocity is a ton and it doesn't seem very proportionate.

What I am asking for is a block that detects whether you're using a trackpad or a mouse

**Comment by SharkPool-SP** [comment]
> If you use a trackpad (like what's on a laptop) and scroll, the velocity isn't that much. If you use a mouse, then the scroll velocity is a ton and it doesn't seem very proportionate.
> 
> 
> 
> What I am asking for is a block that detects whether you're using a trackpad or a mouse

What you're asking depends on mouse scroll sensitivity.
