### ISSUE TITLE
holy moly

### ISSUE THREAD

**Issue by hammouda101010** [SharkPool-SP/SharkPools-Extensions#96]
![Screenshot 2024-09-20 123648](https://github.com/user-attachments/assets/79cbb5fc-ab9a-4d01-97e0-e9518ddf42a6)

![Screenshot 2024-09-20 123850](https://github.com/user-attachments/assets/556ab5b0-d926-455e-9481-c0d8a9417dd1)
Square Block!!!?!?!?!!?!

![meme](https://github.com/user-attachments/assets/558c3c34-52ef-4924-b896-eb004cbc419d)

**Comment by SharkPool-SP** [comment]
Me when arrays use square brackets so it only makes sense to make the blocks square :trollface:

**Comment by hammouda101010** [comment]
> Me when arrays use square brackets so it only makes sense to make the blocks square :trollface:

whats next, are braces will be shaped like hexagons?

**Comment by SharkPool-SP** [comment]
> > Me when arrays use square brackets so it only makes sense to make the blocks square :trollface:
> 
> whats next, are braces will be shaped like hexagons?

nah too confusing
