### ISSUE TITLE
Sprite Effect: Canvas Effect on Bloom is Stacked

### ISSUE THREAD

**Issue by YogaindoCR** [SharkPool-SP/SharkPools-Extensions#98]
There is something weird about adding and deleting canvas filter. After some time, the filter got stacked.

Before:
![image](https://github.com/user-attachments/assets/3ef7e8fe-30e6-45a5-a3cf-fbae612a465c)

After:
![image](https://github.com/user-attachments/assets/5f4898f9-79f4-4757-a187-8891730c5322)

This is the code used:
![image](https://github.com/user-attachments/assets/d6819f4e-bb86-4508-886e-7042b1acf134)

**Comment by SharkPool-SP** [comment]
I noticed this too, its not deleting filters either, they just sometimes stack for some reason, im not 100% sure how to replicate it atm. But I know one of my games suffer from this too

**Comment by YogaindoCR** [comment]
> I noticed this too, its not deleting filters either, they just sometimes stack for some reason, im not 100% sure how to replicate it atm. But I know one of my games suffer from this too

My gueses is...
Using too many filter
There is a canvas effect applied on a forever loop

But these stacking got reset after clearing everything using "remove all canvas filter"

**Comment by SharkPool-SP** [comment]
> > I noticed this too, its not deleting filters either, they just sometimes stack for some reason, im not 100% sure how to replicate it atm. But I know one of my games suffer from this too
> 
> 
> 
> My gueses is...
> 
> Using too many filter
> 
> There is a canvas effect applied on a forever loop
> 
> 
> 
> But these stacking got reset after clearing everything using "remove all canvas filter"

I think it's more to do with the filters being re-applied when going to and from fullscreen and project page

**Comment by SharkPool-SP** [comment]
Update: Figured out why, the *filter* element doesnt get stacked, the **application** to the stage does

**Comment by SharkPool-SP** [comment]
Fixed

**Comment by YogaindoCR** [comment]
> Fixed

Superb!
